### ISSUE TITLE
cyclib error message when building with --prefix option

### ISSUE THREAD

**Issue by gyutaepark** [arfc/cyclus#10]
I still get the cyclib error message when building with --prefix option.
I am currently on Ubuntu 16.04, building cyclus from latest develop.

When I build in .local, without --prefix option, the error message does not appear.

**Comment by gyutaepark** [comment]
Currently put the issue on arfc/cyclus as I am not sure if it is replicable on other systems that build cyclus with --prefix option.

**Comment by katyhuff** [comment]
closed as duplicate.

**Comment by katyhuff** [comment]
What's the status of this?

**Comment by gyutaepark** [comment]
I will test this later today. 
I am not sure at this moment.

**Comment by katyhuff** [comment]
No rush. I'm just going through old issues to determine what can be closed. Thanks!

**Comment by gyutaepark** [comment]
I've finally tested it and the issue has been fixed!
There no longer is an error message regarding cyclib!
I'll close this issue.

**Comment by katyhuff** [comment]
Thanks @gyutaepark !
